/**
 * Build cross-platform single-file binaries via `bun build --compile`.
 *
 * Run with Bun (Node cannot execute this — it depends on Bun's binary file
 * loader and `bun build --compile`):
 *
 *     bun scripts/build-binaries.ts                # all 5 targets
 *     bun scripts/build-binaries.ts linux-x64      # one target
 *     TARGETS=linux-x64,darwin-arm64 bun scripts/build-binaries.ts
 *
 * The script:
 *   1. Walks `assets/`, `ui/`, `starters/` plus `package.json` and
 *      `CHANGELOG.md` and generates `scripts/.generated/runtime-manifest.ts`,
 *      which Bun's binary file loader (`with { type: "file" }`) embeds into
 *      the compiled executable.
 *   2. Invokes `bun build --compile` once per target, writing each binary to
 *      `dist-bin/vibespot-<plat>-<arch>[.exe]`.
 *
 * Outputs are ~90 MB each (Bun runtime + bundled JS + embedded assets).
 *
 * Related: VIB-451 (parent VIB-446).
 */

import { spawnSync } from "node:child_process";
import { mkdirSync, readdirSync, statSync, writeFileSync, readFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

interface Target {
  key: string;
  bunTarget: string;
  ext: string;
}

const REPO_ROOT = resolve(import.meta.dirname, "..");
const DIST_BIN = join(REPO_ROOT, "dist-bin");
const ENTRY = join(REPO_ROOT, "bin", "vibespot-bun-entry.ts");
const MANIFEST_DIR = join(REPO_ROOT, "scripts", ".generated");
const MANIFEST_FILE = join(MANIFEST_DIR, "runtime-manifest.ts");

const ALL_TARGETS: Target[] = [
  { key: "darwin-arm64", bunTarget: "bun-darwin-arm64", ext: "" },
  { key: "darwin-x64", bunTarget: "bun-darwin-x64", ext: "" },
  { key: "linux-x64", bunTarget: "bun-linux-x64", ext: "" },
  { key: "linux-arm64", bunTarget: "bun-linux-arm64", ext: "" },
  { key: "windows-x64", bunTarget: "bun-windows-x64", ext: ".exe" },
];

const EMBED_TREES = ["assets", "ui", "starters"];
const EMBED_FILES = ["package.json", "CHANGELOG.md"];

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      out.push(...walk(full));
    } else if (st.isFile()) {
      out.push(full);
    }
  }
  return out;
}

function collectEmbedPaths(): string[] {
  const paths: string[] = [];
  for (const tree of EMBED_TREES) {
    const abs = join(REPO_ROOT, tree);
    try {
      paths.push(...walk(abs));
    } catch {
      // skip missing dirs (e.g. starters/ stripped in some checkouts)
    }
  }
  for (const file of EMBED_FILES) {
    paths.push(join(REPO_ROOT, file));
  }
  return paths
    .map((p) => relative(REPO_ROOT, p).replace(/\\/g, "/"))
    .sort();
}

function manifestRelativePath(logicalPath: string): string {
  // The manifest lives at scripts/.generated/runtime-manifest.ts. To import
  // a repo-root file, walk up two levels.
  return `../../${logicalPath}`;
}

function generateManifest(): { count: number; version: string } {
  const pkg = JSON.parse(readFileSync(join(REPO_ROOT, "package.json"), "utf-8"));
  const version: string = pkg.version || "dev";

  const paths = collectEmbedPaths();
  mkdirSync(MANIFEST_DIR, { recursive: true });

  const importLines: string[] = [];
  const manifestEntries: string[] = [];
  paths.forEach((logical, idx) => {
    const ident = `f${idx}`;
    importLines.push(
      `import ${ident} from ${JSON.stringify(manifestRelativePath(logical))} with { type: "file" };`,
    );
    manifestEntries.push(`  ${JSON.stringify(logical)}: ${ident},`);
  });

  const body = [
    "// AUTO-GENERATED by scripts/build-binaries.ts — do not edit.",
    "// Lists every packaged file embedded into the `bun --compile` binary.",
    "// Imports use Bun's binary file loader (`with { type: \"file\" }`); at",
    "// runtime each value is a virtual path readable via `Bun.file()`.",
    "",
    ...importLines,
    "",
    `export const RUNTIME_VERSION = ${JSON.stringify(version)};`,
    "export const RUNTIME_FILES: Record<string, string> = {",
    ...manifestEntries,
    "};",
    "",
  ].join("\n");

  writeFileSync(MANIFEST_FILE, body);
  return { count: paths.length, version };
}

function selectedTargets(): Target[] {
  const args = process.argv.slice(2).filter((a) => !a.startsWith("-"));
  const envList = process.env.TARGETS;
  const requested = new Set<string>(
    [...args, ...(envList ? envList.split(",") : [])].map((s) => s.trim()).filter(Boolean),
  );
  if (requested.size === 0) return ALL_TARGETS;
  const out: Target[] = [];
  for (const t of ALL_TARGETS) {
    if (requested.has(t.key) || requested.has(t.bunTarget)) out.push(t);
  }
  if (out.length === 0) {
    console.error(`No matching targets for: ${[...requested].join(", ")}`);
    console.error(`Available: ${ALL_TARGETS.map((t) => t.key).join(", ")}`);
    process.exit(1);
  }
  return out;
}

function buildOne(target: Target): boolean {
  const outFile = join(DIST_BIN, `vibespot-${target.key}${target.ext}`);
  const args = [
    "build",
    "--compile",
    "--target",
    target.bunTarget,
    "--minify",
    ENTRY,
    "--outfile",
    outFile,
  ];
  console.log(`\n→ ${target.bunTarget}  →  ${relative(REPO_ROOT, outFile)}`);
  const result = spawnSync("bun", args, { cwd: REPO_ROOT, stdio: "inherit" });
  if (result.status !== 0) {
    console.error(`  FAILED (exit ${result.status})`);
    return false;
  }
  try {
    const size = statSync(outFile).size;
    console.log(`  ${(size / 1024 / 1024).toFixed(1)} MB`);
  } catch {
    /* ignore */
  }
  return true;
}

function main(): void {
  mkdirSync(DIST_BIN, { recursive: true });
  console.log("Generating runtime manifest...");
  const { count, version } = generateManifest();
  console.log(`  embedded ${count} files, version ${version}`);

  const targets = selectedTargets();
  console.log(`\nBuilding ${targets.length} target(s): ${targets.map((t) => t.key).join(", ")}`);

  const failures: string[] = [];
  for (const target of targets) {
    if (!buildOne(target)) failures.push(target.key);
  }

  if (failures.length > 0) {
    console.error(`\nFailed targets: ${failures.join(", ")}`);
    process.exit(1);
  }
  console.log("\nAll targets built.");
}

main();
